/**
 * The case that matters is the quiet one: a complete JSON response whose
 * `repxContent` stops mid-attribute. Every fixture below that ends early is cut
 * the way a real generation was cut on 2026-08-13 — at 896 bytes, ending
 * `... Name=` — because that is the shape this has to recognise before the user
 * reaches Export and finds a dead file.
 */
import { describe, it, expect } from 'vitest';
import { checkRepxComplete, extractRepxDocument } from './repxTruncation';

const head =
  '<?xml version="1.0" encoding="utf-8"?>\n' +
  '<XtraReportsLayoutSerializer SerializerVersion="23.2.3.0" Ref="0" ' +
  'ControlType="DevExpress.XtraReports.UI.XtraReport" Name="Report1" ' +
  'ReportUnit="HundredthsOfAnInch" Margins="0, 0, 0, 0" PageWidth="850" PageHeight="1100" Version="23.2">';

const whole =
  `${head}
  <Bands>
    <Item1 Ref="1" ControlType="TopMarginBand" Name="TopMargin" HeightF="0" />
    <Item2 Ref="2" ControlType="DetailBand" Name="Detail" HeightF="600">
      <Controls>
        <Item1 Ref="3" ControlType="XRLabel" Name="label1" Text="Invoice" LocationFloat="48,48" SizeF="200,30" />
      </Controls>
    </Item2>
    <Item3 Ref="4" ControlType="BottomMarginBand" Name="BottomMargin" HeightF="0" />
  </Bands>
</XtraReportsLayoutSerializer>`;

describe('checkRepxComplete', () => {
  it('accepts a whole document', () => {
    const result = checkRepxComplete(whole);
    expect(result.complete).toBe(true);
    expect(result.reason).toBe('');
    expect(result.length).toBe(whole.length);
  });

  it('accepts one written as a single line, as the model returns it', () => {
    expect(checkRepxComplete(whole.replace(/\n\s*/g, '')).complete).toBe(true);
  });

  it('catches the real failure: a document that stops mid-attribute', () => {
    // The 2026-08-13 incident, reproduced in miniature.
    const cut = `${head}\n  <Bands>\n    <Item1 Ref="1" ControlType="TopMarginBand" Name=`;
    const result = checkRepxComplete(cut);
    expect(result.complete).toBe(false);
    expect(result.reason).toMatch(/stops mid-tag/);
    // The reason quotes what was being written, because that is what tells a
    // reader of the log it was cut rather than mangled.
    expect(result.reason).toContain('Name=');
  });

  it('catches a document cut between elements, with every tag intact', () => {
    const cut = `${head}\n  <Bands>\n    <Item1 Ref="1" ControlType="TopMarginBand" Name="TopMargin" HeightF="0" />`;
    const result = checkRepxComplete(cut);
    expect(result.complete).toBe(false);
    expect(result.reason).toMatch(/closing <\/XtraReportsLayoutSerializer> is missing/);
  });

  it('catches a root that closes over elements still open', () => {
    // Well-formed-looking at both ends and unopenable in between.
    const cut = `${head}\n  <Bands>\n    <Item2 Ref="2" ControlType="DetailBand" Name="Detail" HeightF="600">\n</XtraReportsLayoutSerializer>`;
    const result = checkRepxComplete(cut);
    expect(result.complete).toBe(false);
    expect(result.reason).toMatch(/never closed/);
  });

  it('reports an empty or missing string rather than throwing', () => {
    for (const value of [undefined, null, '', '   ']) {
      const result = checkRepxComplete(value);
      expect(result.complete, JSON.stringify(value)).toBe(false);
      expect(result.reason).toMatch(/no REPX/);
      expect(result.length).toBe(0);
    }
  });

  it('says the XML never started when the root is absent', () => {
    const result = checkRepxComplete('I could not generate this report.');
    expect(result.complete).toBe(false);
    expect(result.reason).toMatch(/never really started/);
  });

  /**
   * A false positive costs a wasted request and a rewritten report; a false
   * negative costs only the status quo. So anything ambiguous has to come back
   * complete, and these are the ambiguities that would otherwise trip it.
   */
  describe('does not cry truncation over', () => {
    it('an XML declaration or comments containing angle brackets', () => {
      const withComment = whole.replace(
        '<Bands>',
        '<!-- generated by Forma; <Item> tags below --><Bands>'
      );
      expect(checkRepxComplete(withComment).complete).toBe(true);
    });

    it('escaped markup inside an attribute value', () => {
      const withEntities = whole.replace('Text="Invoice"', 'Text="Terms &lt;30 days&gt; &amp; conditions"');
      expect(checkRepxComplete(withEntities).complete).toBe(true);
    });

    it('a nested table, where the closing tags come in a run', () => {
      const table =
        '<Item1 Ref="5" ControlType="XRTable" Name="t" LocationFloat="0,0" SizeF="750,40">' +
        '<Rows><Item1 Ref="6" ControlType="XRTableRow" Name="r" Weight="1">' +
        '<Cells><Item1 Ref="7" ControlType="XRTableCell" Name="c" Text="x" Weight="1" /></Cells>' +
        '</Item1></Rows></Item1>';
      expect(checkRepxComplete(whole.replace(/<Item1 Ref="3"[^>]*\/>/, table)).complete).toBe(true);
    });

    it('trailing whitespace and a newline at the end', () => {
      expect(checkRepxComplete(`${whole}\n\n  `).complete).toBe(true);
    });
  });
});

/**
 * The repair request drops the responseSchema — asking for raw XML instead of
 * XML escaped inside JSON is most of why it has room to finish — and the price
 * is that the reply can arrive dressed up. Everything this strips would make an
 * otherwise perfect document unopenable.
 */
describe('extractRepxDocument', () => {
  it('returns a bare document untouched', () => {
    expect(extractRepxDocument(whole)).toBe(whole);
  });

  it('unwraps a fenced reply', () => {
    expect(extractRepxDocument('```xml\n' + whole + '\n```')).toBe(whole);
  });

  it('drops a sentence of preamble and anything said afterwards', () => {
    const chatty = `Certainly! Here is the corrected report:\n\n${whole}\n\nLet me know if you need changes.`;
    expect(extractRepxDocument(chatty)).toBe(whole);
  });

  it('keeps the XML declaration when there is one', () => {
    expect(extractRepxDocument(whole).startsWith('<?xml')).toBe(true);
  });

  it('starts at the root when the declaration is missing', () => {
    const noDecl = whole.slice(whole.indexOf('<XtraReportsLayoutSerializer'));
    expect(extractRepxDocument(`here you go\n${noDecl}`)).toBe(noDecl);
  });

  it('hands a truncated reply straight to the completeness check rather than judging it', () => {
    // No closing root, so there is nothing to slice to. It must come back with
    // its content intact and be rejected by checkRepxComplete, not silently
    // repaired or emptied here.
    const cut = '```xml\n' + head + '\n  <Bands>\n    <Item1 Ref="1" Name=';
    const out = extractRepxDocument(cut);
    expect(out.startsWith('<?xml')).toBe(true);
    expect(out.endsWith('Name=')).toBe(true);
    expect(checkRepxComplete(out).complete).toBe(false);
  });

  it('returns an empty string for nothing at all', () => {
    for (const value of [undefined, null, '', '  \n ']) {
      expect(extractRepxDocument(value), JSON.stringify(value)).toBe('');
    }
  });

  it('gives back what it was handed when there is no root element', () => {
    expect(extractRepxDocument('  I could not generate this.  ')).toBe('I could not generate this.');
  });
});
