import { User } from 'firebase/auth';
import SiteHeader from './SiteHeader';
import SiteFooter from './SiteFooter';
import SheetRuler from './landing/SheetRuler';
import { Eyebrow } from './landing/sections';

/**
 * The Terms and the Privacy policy, from one component because they are the
 * same page twice: an eyebrow, a heading, a date, and a column of prose.
 *
 * **These describe what the code actually does.** Every claim below is
 * checkable against the repository — where data goes, what is stored, what is
 * not collected. When the app changes, this changes in the same commit; a
 * privacy policy that has drifted from the software is worse than none,
 * because it is a promise nobody is keeping.
 *
 * Both were placeholders until 2026-08-15 (`href="#"`, `data-needs-url`) while
 * the sign-up form asked people to agree to them, which is the one combination
 * that had to end.
 */

const UPDATED = '1 September 2026';

type Section = { heading: string; paragraphs: string[] };

const TERMS: Section[] = [
  {
    heading: 'What Forma is',
    paragraphs: [
      'Forma turns a design you already have — a screenshot, a PDF, or an existing .repx file — into three things: a written specification, an in-browser mockup, and DevExpress XtraReports XML you can open in the DevExpress designer.',
      'It is a personal project, offered free of charge and without a support contract. There is no uptime guarantee, and it may change or stop being available at any time.',
    ],
  },
  {
    heading: 'You bring your own API key',
    paragraphs: [
      'Forma ships without an API key of its own. To generate anything you supply a Google Gemini API key, and your browser calls Google directly with it. Any usage, quota or cost that key incurs is between you and Google, and your use of their API is governed by their terms, not these.',
      'Keep your key to yourself. Anyone who has it can spend against your quota.',
    ],
  },
  {
    heading: 'What you upload, and what comes back',
    paragraphs: [
      'Only upload material you have the right to use. You are responsible for the files you put in and for what you do with the output.',
      'The output is generated by a language model and is not guaranteed to be correct, complete, or fit for any particular purpose. Check the generated .repx in the DevExpress designer before you rely on it. Forma checks the XML is well formed and refuses to hand over a file that is not — that is a structural check, not a promise the report is right.',
    ],
  },
  {
    heading: 'Your account',
    paragraphs: [
      'An account is optional: Forma works signed out, with your work kept in your browser. Signing in exists so your saved projects follow you between machines.',
      'You are responsible for keeping your sign-in details safe. You can change or delete your account at any time from Account settings in the workspace.',
      'Accounts used to break the law, to attack the service, or to abuse other people may be suspended or removed.',
    ],
  },
  {
    heading: 'Liability',
    paragraphs: [
      'Forma is provided "as is", without warranties of any kind, express or implied. To the fullest extent the law allows, the operator is not liable for any loss or damage arising from your use of it — including lost work, lost data, or costs incurred against your own API key.',
      'Nothing here limits liability that cannot be limited by law.',
    ],
  },
  {
    heading: 'Changes',
    paragraphs: [
      'These terms may change as the software does. The date at the top is when they last did. Continuing to use Forma after a change means you accept the current version.',
    ],
  },
];

const PRIVACY: Section[] = [
  {
    heading: 'The short version',
    paragraphs: [
      'Forma collects as little as it can. There are no analytics, no advertising, no tracking pixels and no third-party scripts watching what you do. Nothing is sold or shared with anyone for marketing.',
      'Signed out, two things leave your browser and no others: the request you send to Google with your own API key, and, only if you use the contact form, the message you type into it. Simply opening a page sends nothing to anyone. Who receives each of those is set out under “Who else is involved” below.',
    ],
  },
  {
    heading: 'What is stored when you have an account',
    paragraphs: [
      'Your email address and, if you give one, a display name. These are held by Google Firebase Authentication, which runs the sign-in.',
      'Projects you choose to save: the report title, the conversation in the review panel, the generated specification, layout and XML, and any images you attached. These live in Google Firestore under your account, and the security rules only allow that account to read them.',
      'If you opt in to encrypted sync, an encrypted copy of your Gemini API key. It is encrypted in your browser with a passphrase that never leaves it, so the stored copy is unreadable to anyone who does not know the passphrase — including the operator.',
    ],
  },
  {
    heading: 'Your API key',
    paragraphs: [
      'Your key is held for the browser tab you are working in and is erased when that tab closes. It is never written to disk in readable form and never sent to any server belonging to Forma.',
      'When you generate a report, your browser sends the file and the prompt directly to Google’s Gemini API using your key. What Google does with that is governed by Google’s terms and privacy policy.',
    ],
  },
  {
    heading: 'What is kept in your browser',
    paragraphs: [
      'Signed out, saved projects are kept in your browser’s local storage on that machine only. Forma also remembers small preferences there: the theme, the report configuration, the workspace panel sizes, and which announcements you have read.',
      'Clearing your browser storage removes all of it. Signing out clears the workspace — the uploads, the extracted text and the generated report — so the next person at that browser does not see your work.',
    ],
  },
  {
    heading: 'Who else is involved',
    paragraphs: [
      'Google Firebase provides authentication and the database. Google Gemini generates the report, called directly from your browser with your key. Neither is contacted while you are signed out: opening a page — this one included — sends nothing to either of them. Once you are signed in, your browser does talk to Google on every load, first to check your session is still valid and then to fetch your saved projects, and it holds a connection open so changes to them arrive as they happen.',
      'One other is involved, and only if you act. The contact form is delivered by FormSubmit, which receives the name, email address, subject and message you type into that form and forwards them on as email — only when you press send, only from that one page, and nothing else about you goes with it.',
      'The typefaces used to come from Google Fonts, which meant Google saw the IP address and browser of anyone who opened Forma at all, whether or not they ever signed in or generated anything. They are served from Forma’s own server as of 30 August 2026, so that no longer happens.',
      'Files you upload are prepared in your browser — resized, rendered, parsed — before anything is sent.',
    ],
  },
  {
    heading: 'Deleting your data',
    paragraphs: [
      'Account settings in the workspace has a Delete account action. It removes your saved projects and the encrypted copy of your key along with the account itself. It cannot be undone.',
      'Individual projects can be deleted one at a time from the Projects panel.',
    ],
  },
  {
    heading: 'Contact',
    paragraphs: [
      'Questions about any of this, or a request about your data, can go through the contact page.',
    ],
  },
];

const DOCS = {
  terms: { eyebrow: 'Terms', title: 'Terms of use', sections: TERMS },
  privacy: { eyebrow: 'Privacy', title: 'Privacy policy', sections: PRIVACY },
} as const;

export type LegalDoc = keyof typeof DOCS;

export default function LegalPage({
  doc,
  onEnterWorkspace,
  onSignIn,
  onSignUp,
  user,
  logOut,
  isDarkMode,
  setIsDarkMode,
}: {
  doc: LegalDoc;
  onEnterWorkspace: () => void;
  onSignIn: () => void;
  onSignUp: () => void;
  user: User | null;
  logOut: () => void;
  isDarkMode: boolean;
  setIsDarkMode: (val: boolean) => void;
}) {
  const { eyebrow, title, sections } = DOCS[doc];

  return (
    <div className="landing font-body-lg text-[16px] leading-[1.62] bg-surface text-on-surface min-h-screen flex flex-col">
      <SheetRuler />
      <SiteHeader
        active="none"
        onEnterWorkspace={onEnterWorkspace}
        onSignIn={onSignIn}
        onSignUp={onSignUp}
        user={user}
        logOut={logOut}
        isDarkMode={isDarkMode}
        setIsDarkMode={setIsDarkMode}
      />

      <main className="flex-grow sheet-grid pt-[76px] pb-[104px]">
        <div className="max-w-container-max mx-auto px-margin-desktop">
          <Eyebrow>{eyebrow}</Eyebrow>

          <h1 className="mt-[22px] font-display-lg text-display-lg md:text-[56px] font-extrabold leading-[1.04] tracking-[-0.038em] text-on-surface">
            {title}
          </h1>
          <p className="mt-4 font-code-sm text-[11px] font-medium leading-[1.62] tracking-[0.12em] uppercase text-[color:var(--ink-faint)]">
            Last updated {UPDATED}
          </p>

          {/* One column, measured for reading rather than stretched to the
              container: legal prose nobody can follow is legal prose nobody
              reads. */}
          <div className="mt-11 max-w-[68ch]">
            {sections.map((section, i) => (
              <section key={section.heading} className={i > 0 ? 'mt-10' : ''}>
                <h2 className="font-display-lg text-[22px] font-extrabold leading-[1.25] tracking-[-0.02em] text-on-surface">
                  {section.heading}
                </h2>
                {section.paragraphs.map((text, j) => (
                  <p
                    key={j}
                    className="mt-3.5 font-body-lg text-[15.5px] leading-[1.65] text-on-surface-variant"
                  >
                    {text}
                  </p>
                ))}
              </section>
            ))}

            <p className="mt-12 font-body-lg text-[13.5px] leading-[1.6] text-[color:var(--ink-faint)]">
              Forma is an independent project and this page is written in plain language rather than by a lawyer.
              It describes what the software actually does; where the law of your country gives you more, the law
              wins.
            </p>
          </div>
        </div>
      </main>

      <SiteFooter />
    </div>
  );
}
